// 100 Zitate zu Training, Kraft, mentaler Staerke und Motivation fuer den
// Start-Bildschirm (SplashScreen.tsx). Statisch mitgeliefert - kein
// Laufzeit-Netzwerkzugriff (Grundprinzip der App, siehe gym-app-spec.md).
// Unbelegte/anonyme Gym-Sprueche sind bewusst als "Unbekannt" statt einer
// erfundenen Quelle gekennzeichnet.
export interface Quote {
  text: string
  author: string
}

export const QUOTES: Quote[] = [
  { text: 'The last three or four reps is what makes the muscle grow.', author: 'Arnold Schwarzenegger' },
  { text: 'Strength does not come from winning. Your struggles develop your strengths.', author: 'Arnold Schwarzenegger' },
  { text: 'The mind is the limit. As long as the mind can envision something, you can do it.', author: 'Arnold Schwarzenegger' },
  { text: 'You can have results or excuses, not both.', author: 'Arnold Schwarzenegger' },
  { text: 'Vision creates faith, and faith creates willpower.', author: 'Arnold Schwarzenegger' },
  { text: 'No pain, no gain.', author: 'Arnold Schwarzenegger' },
  { text: 'Everybody wants to be a bodybuilder, but don’t nobody wanna lift no heavy-ass weight.', author: 'Ronnie Coleman' },
  { text: 'Ain’t nothin’ to it but to do it.', author: 'Ronnie Coleman' },
  { text: 'I’m not the strongest, I’m not the biggest, but I’m damn sure the toughest.', author: 'Ronnie Coleman' },
  { text: 'Hard work and training. There’s no secret formula.', author: 'Ronnie Coleman' },
  { text: 'Strength does not come from physical capacity. It comes from an indomitable will.', author: 'Mahatma Gandhi' },
  { text: 'The body achieves what the mind believes.', author: 'James Allen' },
  { text: 'Don’t stop when you’re tired. Stop when you’re done.', author: 'Marilyn Monroe (zugeschrieben)' },
  { text: 'What seems impossible today will one day become your warm-up.', author: 'Unbekannt' },
  { text: 'When you want to achieve greatness, stop asking for permission.', author: 'Unbekannt' },
  { text: 'It’s not about having time, it’s about making time.', author: 'Unbekannt' },
  { text: 'The pain you feel today will be the strength you feel tomorrow.', author: 'Unbekannt' },
  { text: 'Float like a butterfly, sting like a bee.', author: 'Muhammad Ali' },
  { text: 'It isn’t the mountains ahead to climb that wear you out; it’s the pebble in your shoe.', author: 'Muhammad Ali' },
  { text: 'I hated every minute of training, but I said, “Don’t quit. Suffer now and live the rest of your life as a champion.”', author: 'Muhammad Ali' },
  { text: 'Champions aren’t made in gyms. Champions are made from something they have deep inside them: a desire, a dream, a vision.', author: 'Muhammad Ali' },
  { text: 'It’s the repetition of affirmations that leads to belief. And once that belief becomes a deep conviction, things begin to happen.', author: 'Muhammad Ali' },
  { text: 'Fatigue makes cowards of us all.', author: 'Vince Lombardi' },
  { text: 'It’s not whether you get knocked down; it’s whether you get up.', author: 'Vince Lombardi' },
  { text: 'The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.', author: 'Vince Lombardi' },
  { text: 'Winning isn’t everything, but wanting to win is.', author: 'Vince Lombardi' },
  { text: 'It is not the mountain we conquer, but ourselves.', author: 'Edmund Hillary' },
  { text: 'Pain is temporary. Quitting lasts forever.', author: 'Lance Armstrong' },
  { text: 'I’ve failed over and over and over again in my life, and that is why I succeed.', author: 'Michael Jordan' },
  { text: 'I can accept failure, everyone fails at something. But I can’t accept not trying.', author: 'Michael Jordan' },
  { text: 'Some people want it to happen, some wish it would happen, others make it happen.', author: 'Michael Jordan' },
  { text: 'The moment you give up is the moment you let someone else win.', author: 'Kobe Bryant' },
  { text: 'Everything negative – pressure, challenges – is all an opportunity for me to rise.', author: 'Kobe Bryant' },
  { text: 'Rest at the end, not in the middle.', author: 'Unbekannt' },
  { text: 'Sore today, strong tomorrow.', author: 'Unbekannt' },
  { text: 'Sweat is just fat crying.', author: 'Unbekannt' },
  { text: 'The only bad workout is the one that didn’t happen.', author: 'Unbekannt' },
  { text: 'A one-hour workout is 4% of your day. No excuses.', author: 'Unbekannt' },
  { text: 'You don’t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun' },
  { text: 'You miss 100 percent of the shots you don’t take.', author: 'Wayne Gretzky' },
  { text: 'It always seems impossible until it’s done.', author: 'Nelson Mandela' },
  { text: 'The man who moves a mountain begins by carrying away small stones.', author: 'Konfuzius' },
  { text: 'What doesn’t kill you makes you stronger.', author: 'Friedrich Nietzsche' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'The successful warrior is the average man, with laser-like focus.', author: 'Bruce Lee' },
  { text: 'I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.', author: 'Bruce Lee' },
  { text: 'Absorb what is useful, discard what is not, add what is uniquely your own.', author: 'Bruce Lee' },
  { text: 'Don’t count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'Discipline equals freedom.', author: 'Jocko Willink' },
  { text: 'The only easy day was yesterday.', author: 'US Navy SEALs (Sprichwort)' },
  { text: 'You don’t want to be the best of the best. You want to be the only one who does what you do.', author: 'Jocko Willink' },
  { text: 'Suffering is the true test of life.', author: 'David Goggins' },
  { text: 'Most people quit when they hit the wall. I’m going to use that wall to launch myself further.', author: 'David Goggins' },
  { text: 'You are in danger of living a life so comfortable that you will die without ever realizing your true potential.', author: 'David Goggins' },
  { text: 'We are our choices.', author: 'Jean-Paul Sartre' },
  { text: 'Whether you think you can or you think you can’t, you’re right.', author: 'Henry Ford' },
  { text: 'The only limit to our realization of tomorrow will be our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Konfuzius' },
  { text: 'Fall seven times, stand up eight.', author: 'Japanisches Sprichwort' },
  { text: 'A river cuts through rock, not because of its power, but because of its persistence.', author: 'Jim Watkins' },
  { text: 'The groundwork for all happiness is good health.', author: 'Leigh Hunt' },
  { text: 'Take care of your body. It’s the only place you have to live.', author: 'Jim Rohn' },
  { text: 'Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', author: 'Rumi' },
  { text: 'The body is the vehicle of the will.', author: 'Friedrich Nietzsche' },
  { text: 'I will do today what others won’t, so tomorrow I can do what others can’t.', author: 'Jerry Rice' },
  { text: 'You have to expect things of yourself before you can do them.', author: 'Michael Jordan' },
  { text: 'A champion is defined not by their wins but by how they can recover when they fall.', author: 'Serena Williams' },
  { text: 'Adversity causes some men to break; others to break records.', author: 'William Arthur Ward' },
  { text: 'The real workout starts when you want to stop.', author: 'Unbekannt' },
  { text: 'Train insane or remain the same.', author: 'Unbekannt' },
  { text: 'Your body can stand almost anything. It’s your mind you have to convince.', author: 'Unbekannt' },
  { text: 'Strive for progress, not perfection.', author: 'Unbekannt' },
  { text: 'Make yourself proud today.', author: 'Unbekannt' },
  { text: 'Excuses don’t burn calories.', author: 'Unbekannt' },
  { text: 'Wake up. Work out. Kick ass. Repeat.', author: 'Unbekannt' },
  { text: 'A year from now, you’ll wish you had started today.', author: 'Karen Lamb' },
  { text: 'It’s not whether you win or lose, it’s how you play the game.', author: 'Grantland Rice' },
  { text: 'Champions keep playing until they get it right.', author: 'Billie Jean King' },
  { text: 'Pressure is a privilege.', author: 'Billie Jean King' },
  { text: 'I am not afraid of storms, for I am learning how to sail my ship.', author: 'Louisa May Alcott' },
  { text: 'Do something today that your future self will thank you for.', author: 'Sean Patrick Flanery' },
  { text: 'If it doesn’t challenge you, it doesn’t change you.', author: 'Fred DeVito' },
  { text: 'Pain is weakness leaving the body.', author: 'US Marines (Sprichwort)' },
  { text: 'There is no substitute for hard work.', author: 'Thomas Edison' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'I never dreamed about success. I worked for it.', author: 'Estee Lauder' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'Victory is in having done your best. If you’ve done your best, you’ve won.', author: 'Bill Bowerman' },
  { text: 'The man on top of the mountain didn’t fall there.', author: 'Vince Lombardi' },
  { text: 'Do not wait for the perfect moment, take the moment and make it perfect.', author: 'Unbekannt' },
  { text: 'Your only limit is you.', author: 'Unbekannt' },
  { text: 'One more rep than yesterday.', author: 'Unbekannt' },
  { text: 'Discipline is choosing between what you want now and what you want most.', author: 'Abraham Lincoln (zugeschrieben)' },
  { text: 'You can’t build a reputation on what you are going to do.', author: 'Henry Ford' },
  { text: 'Adversity is the first path to truth.', author: 'Lord Byron' },
  { text: 'A smooth sea never made a skilled sailor.', author: 'Franklin D. Roosevelt (zugeschrieben)' },
]
